name: Android CI

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
  
jobs:
  apk:
    name: Generate release builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate apikey.properties
      run: |
          cat <<EOF > apikey.properties
          APPWRITE_PROJECT_ID:"${{ vars.APPWRITE_PROJECT_ID }}"
          APPWRITE_API_KEY:"${{ secrets.APPWRITE_API_KEY }}"
          EOF
    
    - name: Generate keystore.properties
      run: |
          cat <<EOF > keystore.properties
          KEYSTORE_PASSWORD:${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEYSTORE_KEY_PASSWORD:${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_KEY_ALIAS:${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_FILE_PATH:${{ vars.KEYSTORE_STORE_FILE_PATH }}
          EOF
    
    - name: Decode keystore and create jks
      run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks
    
    - name: Generate file name env var
      run: |
          VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)
          DATE=$(date +'%d.%m.%Y')
          BRANCH_NAME=${GITHUB_REF##*/}
          MESSAGE=$(cat << EOF
          AppName-release-${VERSION_NAME}-${BRANCH_NAME}-${DATE}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV
    
    - name: Build release AAB
      run: bash ./gradlew bundleRelease --stacktrace

    - name: Rename AAB 
      run:
        mv "./app/build/outputs/bundle/release/app-release.aab" "./app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab"
      
    - name: Upload debug AAB
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.OUTPUT_NAME }}
        path: app/build/outputs/bundle/release/${{ env.OUTPUT_NAME }}.aab
